### PR TITLE
JAVA-2521, JAVA-2505, JAVA-2506: Module restructuring

### PR DESCRIPTION
**Pull request by jyemin**
JAVA-2521: The restructuring of the modules
JAVA-2505: The MongoDriverInformation move
JAVA-2506: The Automatic-Module-Name

Evergreen patch build: https://evergreen.mongodb.com/version/5a340b19e3c331622100325d

### CODE REVIEW

**Comment by jyemin** [comment]
Rebased to fix a failure in the javadoc target.  The docs target is still failing but I'm not sure why yet.

**Comment by rozza** [comment]
Docs target should be fixed after rebasing master - its missing the options configuration.

**Comment by jyemin** [comment]
@rozza do you have more comments on this one?

**Comment by rozza** [comment]
@jyemin looks like theres some more rebasing todo, but I'm happy with the new layout.

**Comment by jyemin** [comment]
Yeah, pretty much any time anything is added to master, this branch won't rebase cleanly due to all the moved files.

I rebased on master and pushed again.  It all looks good.

**Pull request closed without merging**
